ensures debug is set to false for production deployments

diff --git a/.github/workflows/deploy_prod.yml b/.github/workflows/deploy_prod.yml
--- a/.github/workflows/deploy_prod.yml
+++ b/.github/workflows/deploy_prod.yml
@@ -46,6 +46,13 @@ jobs:
             exit 1
           fi
 
+      - name: Abort if debug set to true
+        run: |
+          if [ "${{ env.EV_ENCLAVE_DEBUG }}" = "true" ]; then
+            echo "::error::This workflow must not be run with debug set to true."
+            exit 1
+          fi
+
       - name: Validate semver
         run: |
           if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
